apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfm-slm-chat
  namespace: tfm-slm
  labels:
    app: tfm-slm-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfm-slm-chat
  template:
    metadata:
      labels:
        app: tfm-slm-chat
    spec:
      containers:
        - name: chat
          image: tfm-slm:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: MODE
              value: "inference"
          envFrom:
            - configMapRef:
                name: tfm-slm-config
            - secretRef:
                name: tfm-slm-aws-secrets
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: tfm-slm-data-pvc
