apiVersion: v1
kind: Secret
metadata:
  name: tfm-slm-aws-secrets
  namespace: tfm-slm
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "YOUR_AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET_ACCESS_KEY"
  AWS_DEFAULT_REGION: "us-east-1"
