apiVersion: v1
kind: Service
metadata:
  name: tfm-slm-chat-service
  namespace: tfm-slm
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: tfm-slm-chat
