apiVersion: batch/v1
kind: Job
metadata:
  name: tfm-slm-training
  namespace: tfm-slm
spec:
  template:
    spec:
      containers:
        - name: training
          image: tfm-slm:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MODE
              value: "train"
          envFrom:
            - configMapRef:
                name: tfm-slm-config
            - secretRef:
                name: tfm-slm-aws-secrets
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      restartPolicy: OnFailure
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: tfm-slm-data-pvc
