apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tfm-slm-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git://host.docker.internal/tfm_slm' # Servido localmente por tu Mac via Git Daemon
    targetRevision: HEAD
    path: argocd-cluster/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tfm-slm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
